### PR TITLE
Do not pass --target if user is not using --target

### LINKED ISSUE #115: Interaction with `-Z instrument-coverage`
I'm trying to generate coverage information for PyO3's procedural macros when running under trybuild. (https://github.com/PyO3/pyo3/pull/1577)

I know that trybuild has to do some dancing with directories and environment to work, and I think part of that is interacting negatively with rustc's nightly `-Zinstrument-coverage` switch. I took a quick look into the guts of the trybuild codebase, but I'm not familiar enough with it to have an intuition what might be the cause.

This is what I'm doing with the PyO3 repo (NB if you try to reproduce you'll need to run my branch `compile-errors-on-coverage` from the above PR, as on `main` branch the whole `trybuild` test is currently skipped on nightly to avoid CI churn with diagnostics and differences in `syn` spans):

```bash
CARGO_TERM_VERBOSE=true RUSTFLAGS="-Zinstrument-coverage" LLVM_PROFILE_FILE="$(pwd)/coverage-%p-%m.profraw" cargo +nightly test --test test_compile_error
grcov . --binary-path target/debug/deps/ -s . -t lcov --branch  -o coverage.lcov
genhtml -o ./target/debug/coverage/ --show-details --highlight --ignore-errors source --legend coverage.lcov
```

The output html report in `target/debug/coverage/index.html` shows that no lines on the pyo3 macros crates were hit, which must be incorrect because I can see the trybuild output in the terminal has executed pyo3 code.

Replacing `test_compile_error` in the procedure above with a different test (e.g. `test_pymethods`) yields a correct result where the macros do indeed show coverage information.

My guess is that `trybuild` having a separate `--target` directory is likely to be the root cause, but some quick experimentation with this myself (e.g. pointing the `grcov` invocation to the different directory) hasn't yielded any results.

Thanks in advance for any help with this.

### PR DESCRIPTION
**Pull request by taiki-e**
When `--target` flag is passed, cargo does not pass `RUSTFLAGS` to rustc when building proc-macro and build script even if the host and target triples are the same. Therefore, if we always pass `--target` to cargo, tools such as coverage that require `RUSTFLAGS` do not work for tests run by trybuild.

To avoid that problem, this patch change to not pass `--target` to cargo if we know that it has not been passed.

Cargo does not have a way to tell the build script whether `--target` has been passed or not, so we use the following heuristic:

- The host and target triples are the same.
- And `RUSTFLAGS` is available when *building* the build script.

Note that the second is when building, not when running. This is due to:

- After rust-lang/cargo#9601, cargo does not pass `RUSTFLAGS` to the build script when running. (see also https://github.com/alexcrichton/proc-macro2/issues/293)
- `CARGO_ENCODED_RUSTFLAGS`, which was introduced in rust-lang/cargo#9601, cannot be used for this purpose because it contains the value of `RUSTFLAGS` even if --target is passed and the host and target triples are the same.

Fixes #115

--- 

Tested with a case where using [cargo-llvm-cov](https://github.com/taiki-e/cargo-llvm-cov) and a case where using llvm-cov directly without any third party tools. See https://github.com/taiki-e/cargo-llvm-cov/pull/44#issuecomment-894656727 for one of the cases I actually tested.

I have not tested the other tools, but it is likely that they will need some change like https://github.com/taiki-e/cargo-llvm-cov/pull/44 on their side.

I also tested a case of #90, with a way discripted in #90.

> Tested with `cargo test --target x86_64-unknown-linux-gnu` inside a crate that has `[build] target = "thumbv7m-none-eabi"` in .cargo/config.

### CODE REVIEW

File: build.rs [hunk 1]
```diff
@@ -5,7 +5,34 @@ use std::path::Path;
...
+    // as coverage that require RUSTFLAGS do not work for tests run by trybuild.
+    //
+    // To avoid that problem, do not pass --target to cargo if we know that it
+    // has not been passed.
+    //
+    // Cargo does not have a way to tell the build script whether --target has
+    // been passed or not, so we use the following heuristic:
+    //
+    // - The host and target triples are the same.
+    // - And RUSTFLAGS is available when *building* the build script.
```
Comment (taiki-e) [inline build.rs:22]: I think this shouldn't be a problem because the build script will be rebuilt when RUSTFLAGS is changed, but I may have missed something.

**Review by dtolnay — APPROVED** [review]
Thanks! This is great.
