### PR TITLE
fix feature flag detection on Windows

### LINKED ISSUE #9: Support features in test cases
Currently all test cases are only built with the default feature set.

### PR DESCRIPTION
**Pull request by abonander**
closes #9 

Fixes the error for me on Windows.

### CODE REVIEW

File: src/features.rs [hunk 1]
```diff
@@ -32,9 +32,16 @@ fn try_find() -> Result<Vec<String>, Ignored> {
     // The hash at the end is ascii so not lossy, rest of conversion doesn't
     // matter.
     let test_binary_lossy = test_binary.to_string_lossy();
-    let hash = test_binary_lossy
-        .get(test_binary_lossy.len() - 17..)
-        .ok_or(Ignored)?;
+    let hash = if cfg!(windows) {
```
Comment (abonander) [inline src/features.rs]: This will break if someone is cross-compiling tests. Do we care?

Comment (dtolnay) [reply src/features.rs]: Nope, don't care. They can send a fix if it comes up. Thanks for flagging though!

**Comment by dtolnay** [comment]
Published in 1.0.20.
